### PR TITLE
Update constants.toml

### PR DESCRIPTION
**Pull request by not-john**
more radios!!

### CODE REVIEW

**Comment by ducc** [comment]
god bless u kind sir !!!

**Comment by not-john** [comment]
no problem!! 😄 


_now where is my payment!!_

**Comment by ducc** [comment]
In YOur Ass LOL XD

**Comment by not-john** [comment]
LOL WOW XD

**Comment by ducc** [comment]
!!!

**Comment by not-john** [comment]
GIVE!!

**Pull request merged**
