### PR TITLE
Gradle & purge command

### PR DESCRIPTION
**Pull request by Dot-Rar**
Ur all so slow so I did it for you. Also gradle > maven.

### CODE REVIEW

**Comment by ducc** [comment]
fuck Gradle fuck Gradle fuck Gradle fuck Gradle fuck Gradle fuck Gradle fuck Gradle fuck Gradle fuck Gradle fuck Gradle fuck Gradle fuck Gradle fuck Gradle fuck Gradle fuck Gradle fuck Gradle fuck Gradle fuck Gradle fuck Gradle fuck Gradle fuck Gradle fuck Gradle fuck Gradle fuck Gradle fuck Gradle

**Comment by Dot-Rar** [comment]
fuck maven fuck maven fuck maven fuck maven fuck maven fuck maven fuck maven fuck maven fuck maven fuck maven fuck maven fuck maven fuck maven fuck maven fuck maven fuck maven fuck maven fuck maven fuck maven fuck maven fuck maven fuck maven fuck maven fuck maven fuck maven fuck maven fuck maven fuck maven fuck maven fuck maven fuck maven fuck maven fuck maven fuck maven fuck maven fuck maven fuck maven fuck maven fuck maven fuck maven fuck maven fuck maven

**Comment by bramhaag** [comment]
that's one shitty build.gradle, doesn't even shade dependencies... nice job

**Comment by Dot-Rar** [comment]
yes it does faggot

**Comment by bramhaag** [comment]
doenst compile

**Comment by ducc** [comment]
srsly tho remove the gradle dont want or need to change build systems

**Comment by Dot-Rar** [comment]
henlo am syrian refugee pls show bob and vaganene and accept PR thank

**Comment by ducc** [comment]
delete gradle :)

**Comment by Dot-Rar** [comment]
no

**Comment by Dot-Rar** [comment]
accept it already autist

**Comment by ducc** [comment]
ill never accept you

**Comment by Dot-Rar** [comment]
u fucking wot

**Pull request closed without merging**
