### PR TITLE
All radio stations are now in alphabetical order

### PR DESCRIPTION
**Pull request by Xastreh**
This pull request does nothing but make all the radio stations in alphabetical order. P.S. I just used a alphabetical order generator to do this so... yeah. It didn't take me long to do this.

### CODE REVIEW

**Comment by zeyla** [comment]
We don't seem to use any specific ordering as it is in terms of locale, but I'd recommend we switch to using the `en_GB.UTF-8` locale for standardized sorting. This roughly means that keys starting with special characters are first, then numbers are alphabetically before capitalized letters (0 before 1 before 2 etc.), which are alphabetically before lowercase letters (A, B, C, ... Y, Z, a, b, c, ... y, z).

An example:
```toml
[radioStations]
  "100% NL": "url"
  "104.6 RTL Neue Hits": "url"
  "1Mix House": "url"
  "1Mix Trance": "url"
  "89.0 RTL": "url"
  "977": "url"
  "977 Country Hits": "url"
  "98Radio Rock": "url"
  "ABC Brisbane": "url"
  # those starting with a lowercase are at the very bottom
  "gem": "url"
```

**Comment by Xastreh** [comment]
Ahh alright. Now that I know this, there was no point in turning the radio station name from "gem" to "Gem" because it would probably still end up on the bottom of the list on the bot when you do `!!!radio`. And it's good you are hopefully switching to `en_GB.UTF-8` soon because it's a pain to go online, search up a generator where you can put everything in order, and put in back in GitHub because like for example the "977" and  the "977 Country Hits", the "977" radio station got moved below the "977 Country Hits" station because it seems to do spaces first then the numbers itself which is weird so yeah. This is good to know. ;D

**Comment by bramhaag** [comment]
Eh, just so you know, dabbot already prints the stations out [in alphabetical order](https://github.com/ducc/JavaMusicBot/blob/master/src/main/java/ovh/not/javamusicbot/Constants.java#L8) anyway.

**Comment by gmantsang** [comment]
Oh me and xastreh were just following what john wanted :|

**Pull request closed without merging**
